### ISSUE TITLE
Add a new branch to plan route of trip

### ISSUE THREAD

**Issue by Thongvor** [Thongvor/BestTrip_v3000#1]
choose the best route

**Comment by Thongvor** [comment]
We need to choose a route for our trip.
Any variants?

**Comment by SimonMaha** [comment]
Daria, we are waiting for results!

**Comment by DombrovskayaDaria** [comment]
We can start from Europe, then North America, Latin America, Asia, Australia and finish with Africa&the Middle East

**Comment by OlyaKhomyn** [comment]
norm
