### ISSUE TITLE
Add a new branch to choose kind of trip(autostop, train, plane, etc.)

### ISSUE THREAD

**Issue by Thongvor** [Thongvor/BestTrip_v3000#2]
We need to choose a way to travel

**Comment by Thongvor** [comment]
Now we need to choose the way we want to travel
It may be more than one kind of transport to choose from.
What kind of transport do you prefer?

Any wishes and suggestions?

**Comment by OlyaKhomyn** [comment]
autostop

**Comment by Thongvor** [comment]
I think we can choose autostop to cut our costs
But sometimes we can use a plane if it will possible to buy a low-cost ticket.

**Comment by DombrovskayaDaria** [comment]
autostop and plane to cross the ocean

**Comment by OlyaKhomyn** [comment]
Perfect solution
